use std::fmt::{Display, Formatter};
use sdl3::gamepad::{Axis, Button};
use serde::{Deserialize, Serialize};
use frozen_collections::Scalar;
use sdl3::keyboard;

#[derive(Copy, Clone, Debug)]
pub enum Kind {
    Up,
    Down,
    Axis,
}

#[derive(Copy, Clone, Debug)]
pub struct Event {
    pub keycode: Keycode,
    pub kind: Kind,
    pub value: i16,
}

#[derive(
    Copy, Clone, Debug, Hash, PartialEq, Eq, Deserialize, Serialize, Scalar, Ord, PartialOrd
)]
pub enum Keycode {
    ScancodeMask,
    Unknown,
    Return,
    Escape,
    Backspace,
    Tab,
    Space,
    Exclaim,
    DblApostrophe,
    Hash,
    Dollar,
    Percent,
    Ampersand,
    Apostrophe,
    LeftParen,
    RightParen,
    Asterisk,
    Plus,
    Comma,
    Minus,
    Period,
    Slash,
    _0,
    _1,
    _2,
    _3,
    _4,
    _5,
    _6,
    _7,
    _8,
    _9,
    Colon,
    Semicolon,
    Less,
    Equals,
    Greater,
    Question,
    At,
    LeftBracket,
    Backslash,
    RightBracket,
    Caret,
    Underscore,
    Grave,
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    LeftBrace,
    Pipe,
    RightBrace,
    Tilde,
    Delete,
    PlusMinus,
    CapsLock,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    PrintScreen,
    ScrollLock,
    Pause,
    Insert,
    Home,
    PageUp,
    End,
    PageDown,
    Right,
    Left,
    Down,
    Up,
    NumLockClear,
    KpDivide,
    KpMultiply,
    KpMinus,
    KpPlus,
    KpEnter,
    Kp1,
    Kp2,
    Kp3,
    Kp4,
    Kp5,
    Kp6,
    Kp7,
    Kp8,
    Kp9,
    Kp0,
    KpPeriod,
    Application,
    Power,
    KpEquals,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    F21,
    F22,
    F23,
    F24,
    Execute,
    Help,
    Menu,
    Select,
    Stop,
    Again,
    Undo,
    Cut,
    Copy,
    Paste,
    Find,
    Mute,
    VolumeUp,
    VolumeDown,
    KpComma,
    KpEqualsAs400,
    AltErase,
    SysReq,
    Cancel,
    Clear,
    Prior,
    Return2,
    Separator,
    Out,
    Oper,
    ClearAgain,
    CrSel,
    ExSel,
    Kp00,
    Kp000,
    ThousandsSeparator,
    DecimalSeparator,
    CurrencyUnit,
    CurrencySubunit,
    KpLeftParen,
    KpRightParen,
    KpLeftBrace,
    KpRightBrace,
    KpTab,
    KpBackspace,
    KpA,
    KpB,
    KpC,
    KpD,
    KpE,
    KpF,
    KpXor,
    KpPower,
    KpPercent,
    KpLess,
    KpGreater,
    KpAmpersand,
    KpDblAmpersand,
    KpVerticalBar,
    KpDblVerticalBar,
    KpColon,
    KpHash,
    KpSpace,
    KpAt,
    KpExclam,
    KpMemStore,
    KpMemRecall,
    KpMemClear,
    KpMemAdd,
    KpMemSubtract,
    KpMemMultiply,
    KpMemDivide,
    KpPlusMinus,
    KpClear,
    KpClearEntry,
    KpBinary,
    KpOctal,
    KpDecimal,
    KpHexadecimal,
    LCtrl,
    LShift,
    LAlt,
    LGui,
    RCtrl,
    RShift,
    RAlt,
    RGui,
    Mode,
    Sleep,
    Wake,
    ChannelIncrement,
    ChannelDecrement,
    MediaPlay,
    MediaPause,
    MediaRecord,
    MediaFastForward,
    MediaRewind,
    MediaNextTrack,
    MediaPreviousTrack,
    MediaStop,
    MediaEject,
    MediaPlayPause,
    MediaSelect,
    AcNew,
    AcOpen,
    AcClose,
    AcExit,
    AcSave,
    AcPrint,
    AcProperties,
    AcSearch,
    AcHome,
    AcBack,
    AcForward,
    AcStop,
    AcRefresh,
    AcBookmarks,
    SoftLeft,
    SoftRight,
    Call,
    EndCall,
    
    North,
    East,
    South,
    West,
    Back,
    Guide,
    Start,
    LeftStick,
    RightStick,
    LeftShoulder,
    RightShoulder,
    DPadUp,
    DPadDown,
    DPadLeft,
    DPadRight,
    Misc1,
    Misc2,
    Misc3,
    Misc4,
    Misc5,
    RightPaddle1,
    LeftPaddle1,
    RightPaddle2,
    LeftPaddle2,
    Touchpad,

    LeftX,
    LeftY,
    RightX,
    RightY,
    TriggerLeft,
    TriggerRight,
}

impl Into<u16> for Keycode {
    fn into(self) -> u16 {
        self as u16
    }
}

impl Into<usize> for Keycode {
    fn into(self) -> usize {
        self as usize
    }
}

impl Into<u16> for &Keycode {
    fn into(self) -> u16 {
        *self as u16
    }
}

impl Into<usize> for &Keycode {
    fn into(self) -> usize {
        *self as usize
    }
}

impl Display for Keycode {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        write!(f, "{self:?}")
    }
}


impl From<Axis> for Keycode {
    fn from(axis: Axis) -> Self {
        match axis {
            Axis::LeftX => Keycode::LeftX,
            Axis::LeftY => Keycode::LeftY,
            Axis::RightX => Keycode::RightX,
            Axis::RightY => Keycode::RightY,
            Axis::TriggerLeft => Keycode::TriggerLeft,
            Axis::TriggerRight => Keycode::TriggerRight,
        }
    }
}

impl From<Button> for Keycode {
    fn from(button: Button) -> Self {
        match button {
            Button::North => Keycode::North,
            Button::East => Keycode::East,
            Button::South => Keycode::South,
            Button::West => Keycode::West,
            Button::Back => Keycode::Back,
            Button::Guide => Keycode::Guide,
            Button::Start => Keycode::Start,
            Button::LeftStick => Keycode::LeftStick,
            Button::RightStick => Keycode::RightStick,
            Button::LeftShoulder => Keycode::LeftShoulder,
            Button::RightShoulder => Keycode::RightShoulder,
            Button::DPadUp => Keycode::DPadUp,
            Button::DPadDown => Keycode::DPadDown,
            Button::DPadLeft => Keycode::DPadLeft,
            Button::DPadRight => Keycode::DPadRight,
            Button::Misc1 => Keycode::Misc1,
            Button::Misc2 => Keycode::Misc2,
            Button::Misc3 => Keycode::Misc3,
            Button::Misc4 => Keycode::Misc4,
            Button::Misc5 => Keycode::Misc5,
            Button::RightPaddle1 => Keycode::RightPaddle1,
            Button::LeftPaddle1 => Keycode::LeftPaddle1,
            Button::RightPaddle2 => Keycode::RightPaddle2,
            Button::LeftPaddle2 => Keycode::LeftPaddle2,
            Button::Touchpad => Keycode::Touchpad,
        }
    }
}

impl From<keyboard::Keycode> for Keycode {
    fn from(keycode: keyboard::Keycode) -> Self {
        match keycode {
            keyboard::Keycode::ScancodeMask => Keycode::ScancodeMask,
            keyboard::Keycode::Unknown => Keycode::Unknown,
            keyboard::Keycode::Return => Keycode::Return,
            keyboard::Keycode::Escape => Keycode::Escape,
            keyboard::Keycode::Backspace => Keycode::Backspace,
            keyboard::Keycode::Tab => Keycode::Tab,
            keyboard::Keycode::Space => Keycode::Space,
            keyboard::Keycode::Exclaim => Keycode::Exclaim,
            keyboard::Keycode::DblApostrophe => Keycode::DblApostrophe,
            keyboard::Keycode::Hash => Keycode::Hash,
            keyboard::Keycode::Dollar => Keycode::Dollar,
            keyboard::Keycode::Percent => Keycode::Percent,
            keyboard::Keycode::Ampersand => Keycode::Ampersand,
            keyboard::Keycode::Apostrophe => Keycode::Apostrophe,
            keyboard::Keycode::LeftParen => Keycode::LeftParen,
            keyboard::Keycode::RightParen => Keycode::RightParen,
            keyboard::Keycode::Asterisk => Keycode::Asterisk,
            keyboard::Keycode::Plus => Keycode::Plus,
            keyboard::Keycode::Comma => Keycode::Comma,
            keyboard::Keycode::Minus => Keycode::Minus,
            keyboard::Keycode::Period => Keycode::Period,
            keyboard::Keycode::Slash => Keycode::Slash,
            keyboard::Keycode::_0 => Keycode::_0,
            keyboard::Keycode::_1 => Keycode::_1,
            keyboard::Keycode::_2 => Keycode::_2,
            keyboard::Keycode::_3 => Keycode::_3,
            keyboard::Keycode::_4 => Keycode::_4,
            keyboard::Keycode::_5 => Keycode::_5,
            keyboard::Keycode::_6 => Keycode::_6,
            keyboard::Keycode::_7 => Keycode::_7,
            keyboard::Keycode::_8 => Keycode::_8,
            keyboard::Keycode::_9 => Keycode::_9,
            keyboard::Keycode::Colon => Keycode::Colon,
            keyboard::Keycode::Semicolon => Keycode::Semicolon,
            keyboard::Keycode::Less => Keycode::Less,
            keyboard::Keycode::Equals => Keycode::Equals,
            keyboard::Keycode::Greater => Keycode::Greater,
            keyboard::Keycode::Question => Keycode::Question,
            keyboard::Keycode::At => Keycode::At,
            keyboard::Keycode::LeftBracket => Keycode::LeftBracket,
            keyboard::Keycode::Backslash => Keycode::Backslash,
            keyboard::Keycode::RightBracket => Keycode::RightBracket,
            keyboard::Keycode::Caret => Keycode::Caret,
            keyboard::Keycode::Underscore => Keycode::Underscore,
            keyboard::Keycode::Grave => Keycode::Grave,
            keyboard::Keycode::A => Keycode::A,
            keyboard::Keycode::B => Keycode::B,
            keyboard::Keycode::C => Keycode::C,
            keyboard::Keycode::D => Keycode::D,
            keyboard::Keycode::E => Keycode::E,
            keyboard::Keycode::F => Keycode::F,
            keyboard::Keycode::G => Keycode::G,
            keyboard::Keycode::H => Keycode::H,
            keyboard::Keycode::I => Keycode::I,
            keyboard::Keycode::J => Keycode::J,
            keyboard::Keycode::K => Keycode::K,
            keyboard::Keycode::L => Keycode::L,
            keyboard::Keycode::M => Keycode::M,
            keyboard::Keycode::N => Keycode::N,
            keyboard::Keycode::O => Keycode::O,
            keyboard::Keycode::P => Keycode::P,
            keyboard::Keycode::Q => Keycode::Q,
            keyboard::Keycode::R => Keycode::R,
            keyboard::Keycode::S => Keycode::S,
            keyboard::Keycode::T => Keycode::T,
            keyboard::Keycode::U => Keycode::U,
            keyboard::Keycode::V => Keycode::V,
            keyboard::Keycode::W => Keycode::W,
            keyboard::Keycode::X => Keycode::X,
            keyboard::Keycode::Y => Keycode::Y,
            keyboard::Keycode::Z => Keycode::Z,
            keyboard::Keycode::LeftBrace => Keycode::LeftBrace,
            keyboard::Keycode::Pipe => Keycode::Pipe,
            keyboard::Keycode::RightBrace => Keycode::RightBrace,
            keyboard::Keycode::Tilde => Keycode::Tilde,
            keyboard::Keycode::Delete => Keycode::Delete,
            keyboard::Keycode::PlusMinus => Keycode::PlusMinus,
            keyboard::Keycode::CapsLock => Keycode::CapsLock,
            keyboard::Keycode::F1 => Keycode::F1,
            keyboard::Keycode::F2 => Keycode::F2,
            keyboard::Keycode::F3 => Keycode::F3,
            keyboard::Keycode::F4 => Keycode::F4,
            keyboard::Keycode::F5 => Keycode::F5,
            keyboard::Keycode::F6 => Keycode::F6,
            keyboard::Keycode::F7 => Keycode::F7,
            keyboard::Keycode::F8 => Keycode::F8,
            keyboard::Keycode::F9 => Keycode::F9,
            keyboard::Keycode::F10 => Keycode::F10,
            keyboard::Keycode::F11 => Keycode::F11,
            keyboard::Keycode::F12 => Keycode::F12,
            keyboard::Keycode::PrintScreen => Keycode::PrintScreen,
            keyboard::Keycode::ScrollLock => Keycode::ScrollLock,
            keyboard::Keycode::Pause => Keycode::Pause,
            keyboard::Keycode::Insert => Keycode::Insert,
            keyboard::Keycode::Home => Keycode::Home,
            keyboard::Keycode::PageUp => Keycode::PageUp,
            keyboard::Keycode::End => Keycode::End,
            keyboard::Keycode::PageDown => Keycode::PageDown,
            keyboard::Keycode::Right => Keycode::Right,
            keyboard::Keycode::Left => Keycode::Left,
            keyboard::Keycode::Down => Keycode::Down,
            keyboard::Keycode::Up => Keycode::Up,
            keyboard::Keycode::NumLockClear => Keycode::NumLockClear,
            keyboard::Keycode::KpDivide => Keycode::KpDivide,
            keyboard::Keycode::KpMultiply => Keycode::KpMultiply,
            keyboard::Keycode::KpMinus => Keycode::KpMinus,
            keyboard::Keycode::KpPlus => Keycode::KpPlus,
            keyboard::Keycode::KpEnter => Keycode::KpEnter,
            keyboard::Keycode::Kp1 => Keycode::Kp1,
            keyboard::Keycode::Kp2 => Keycode::Kp2,
            keyboard::Keycode::Kp3 => Keycode::Kp3,
            keyboard::Keycode::Kp4 => Keycode::Kp4,
            keyboard::Keycode::Kp5 => Keycode::Kp5,
            keyboard::Keycode::Kp6 => Keycode::Kp6,
            keyboard::Keycode::Kp7 => Keycode::Kp7,
            keyboard::Keycode::Kp8 => Keycode::Kp8,
            keyboard::Keycode::Kp9 => Keycode::Kp9,
            keyboard::Keycode::Kp0 => Keycode::Kp0,
            keyboard::Keycode::KpPeriod => Keycode::KpPeriod,
            keyboard::Keycode::Application => Keycode::Application,
            keyboard::Keycode::Power => Keycode::Power,
            keyboard::Keycode::KpEquals => Keycode::KpEquals,
            keyboard::Keycode::F13 => Keycode::F13,
            keyboard::Keycode::F14 => Keycode::F14,
            keyboard::Keycode::F15 => Keycode::F15,
            keyboard::Keycode::F16 => Keycode::F16,
            keyboard::Keycode::F17 => Keycode::F17,
            keyboard::Keycode::F18 => Keycode::F18,
            keyboard::Keycode::F19 => Keycode::F19,
            keyboard::Keycode::F20 => Keycode::F20,
            keyboard::Keycode::F21 => Keycode::F21,
            keyboard::Keycode::F22 => Keycode::F22,
            keyboard::Keycode::F23 => Keycode::F23,
            keyboard::Keycode::F24 => Keycode::F24,
            keyboard::Keycode::Execute => Keycode::Execute,
            keyboard::Keycode::Help => Keycode::Help,
            keyboard::Keycode::Menu => Keycode::Menu,
            keyboard::Keycode::Select => Keycode::Select,
            keyboard::Keycode::Stop => Keycode::Stop,
            keyboard::Keycode::Again => Keycode::Again,
            keyboard::Keycode::Undo => Keycode::Undo,
            keyboard::Keycode::Cut => Keycode::Cut,
            keyboard::Keycode::Copy => Keycode::Copy,
            keyboard::Keycode::Paste => Keycode::Paste,
            keyboard::Keycode::Find => Keycode::Find,
            keyboard::Keycode::Mute => Keycode::Mute,
            keyboard::Keycode::VolumeUp => Keycode::VolumeUp,
            keyboard::Keycode::VolumeDown => Keycode::VolumeDown,
            keyboard::Keycode::KpComma => Keycode::KpComma,
            keyboard::Keycode::KpEqualsAs400 => Keycode::KpEqualsAs400,
            keyboard::Keycode::AltErase => Keycode::AltErase,
            keyboard::Keycode::SysReq => Keycode::SysReq,
            keyboard::Keycode::Cancel => Keycode::Cancel,
            keyboard::Keycode::Clear => Keycode::Clear,
            keyboard::Keycode::Prior => Keycode::Prior,
            keyboard::Keycode::Return2 => Keycode::Return2,
            keyboard::Keycode::Separator => Keycode::Separator,
            keyboard::Keycode::Out => Keycode::Out,
            keyboard::Keycode::Oper => Keycode::Oper,
            keyboard::Keycode::ClearAgain => Keycode::ClearAgain,
            keyboard::Keycode::CrSel => Keycode::CrSel,
            keyboard::Keycode::ExSel => Keycode::ExSel,
            keyboard::Keycode::Kp00 => Keycode::Kp00,
            keyboard::Keycode::Kp000 => Keycode::Kp000,
            keyboard::Keycode::ThousandsSeparator => Keycode::ThousandsSeparator,
            keyboard::Keycode::DecimalSeparator => Keycode::DecimalSeparator,
            keyboard::Keycode::CurrencyUnit => Keycode::CurrencyUnit,
            keyboard::Keycode::CurrencySubunit => Keycode::CurrencySubunit,
            keyboard::Keycode::KpLeftParen => Keycode::KpLeftParen,
            keyboard::Keycode::KpRightParen => Keycode::KpRightParen,
            keyboard::Keycode::KpLeftBrace => Keycode::KpLeftBrace,
            keyboard::Keycode::KpRightBrace => Keycode::KpRightBrace,
            keyboard::Keycode::KpTab => Keycode::KpTab,
            keyboard::Keycode::KpBackspace => Keycode::KpBackspace,
            keyboard::Keycode::KpA => Keycode::KpA,
            keyboard::Keycode::KpB => Keycode::KpB,
            keyboard::Keycode::KpC => Keycode::KpC,
            keyboard::Keycode::KpD => Keycode::KpD,
            keyboard::Keycode::KpE => Keycode::KpE,
            keyboard::Keycode::KpF => Keycode::KpF,
            keyboard::Keycode::KpXor => Keycode::KpXor,
            keyboard::Keycode::KpPower => Keycode::KpPower,
            keyboard::Keycode::KpPercent => Keycode::KpPercent,
            keyboard::Keycode::KpLess => Keycode::KpLess,
            keyboard::Keycode::KpGreater => Keycode::KpGreater,
            keyboard::Keycode::KpAmpersand => Keycode::KpAmpersand,
            keyboard::Keycode::KpDblAmpersand => Keycode::KpDblAmpersand,
            keyboard::Keycode::KpVerticalBar => Keycode::KpVerticalBar,
            keyboard::Keycode::KpDblVerticalBar => Keycode::KpDblVerticalBar,
            keyboard::Keycode::KpColon => Keycode::KpColon,
            keyboard::Keycode::KpHash => Keycode::KpHash,
            keyboard::Keycode::KpSpace => Keycode::KpSpace,
            keyboard::Keycode::KpAt => Keycode::KpAt,
            keyboard::Keycode::KpExclam => Keycode::KpExclam,
            keyboard::Keycode::KpMemStore => Keycode::KpMemStore,
            keyboard::Keycode::KpMemRecall => Keycode::KpMemRecall,
            keyboard::Keycode::KpMemClear => Keycode::KpMemClear,
            keyboard::Keycode::KpMemAdd => Keycode::KpMemAdd,
            keyboard::Keycode::KpMemSubtract => Keycode::KpMemSubtract,
            keyboard::Keycode::KpMemMultiply => Keycode::KpMemMultiply,
            keyboard::Keycode::KpMemDivide => Keycode::KpMemDivide,
            keyboard::Keycode::KpPlusMinus => Keycode::KpPlusMinus,
            keyboard::Keycode::KpClear => Keycode::KpClear,
            keyboard::Keycode::KpClearEntry => Keycode::KpClearEntry,
            keyboard::Keycode::KpBinary => Keycode::KpBinary,
            keyboard::Keycode::KpOctal => Keycode::KpOctal,
            keyboard::Keycode::KpDecimal => Keycode::KpDecimal,
            keyboard::Keycode::KpHexadecimal => Keycode::KpHexadecimal,
            keyboard::Keycode::LCtrl => Keycode::LCtrl,
            keyboard::Keycode::LShift => Keycode::LShift,
            keyboard::Keycode::LAlt => Keycode::LAlt,
            keyboard::Keycode::LGui => Keycode::LGui,
            keyboard::Keycode::RCtrl => Keycode::RCtrl,
            keyboard::Keycode::RShift => Keycode::RShift,
            keyboard::Keycode::RAlt => Keycode::RAlt,
            keyboard::Keycode::RGui => Keycode::RGui,
            keyboard::Keycode::Mode => Keycode::Mode,
            keyboard::Keycode::Sleep => Keycode::Sleep,
            keyboard::Keycode::Wake => Keycode::Wake,
            keyboard::Keycode::ChannelIncrement => Keycode::ChannelIncrement,
            keyboard::Keycode::ChannelDecrement => Keycode::ChannelDecrement,
            keyboard::Keycode::MediaPlay => Keycode::MediaPlay,
            keyboard::Keycode::MediaPause => Keycode::MediaPause,
            keyboard::Keycode::MediaRecord => Keycode::MediaRecord,
            keyboard::Keycode::MediaFastForward => Keycode::MediaFastForward,
            keyboard::Keycode::MediaRewind => Keycode::MediaRewind,
            keyboard::Keycode::MediaNextTrack => Keycode::MediaNextTrack,
            keyboard::Keycode::MediaPreviousTrack => Keycode::MediaPreviousTrack,
            keyboard::Keycode::MediaStop => Keycode::MediaStop,
            keyboard::Keycode::MediaEject => Keycode::MediaEject,
            keyboard::Keycode::MediaPlayPause => Keycode::MediaPlayPause,
            keyboard::Keycode::MediaSelect => Keycode::MediaSelect,
            keyboard::Keycode::AcNew => Keycode::AcNew,
            keyboard::Keycode::AcOpen => Keycode::AcOpen,
            keyboard::Keycode::AcClose => Keycode::AcClose,
            keyboard::Keycode::AcExit => Keycode::AcExit,
            keyboard::Keycode::AcSave => Keycode::AcSave,
            keyboard::Keycode::AcPrint => Keycode::AcPrint,
            keyboard::Keycode::AcProperties => Keycode::AcProperties,
            keyboard::Keycode::AcSearch => Keycode::AcSearch,
            keyboard::Keycode::AcHome => Keycode::AcHome,
            keyboard::Keycode::AcBack => Keycode::AcBack,
            keyboard::Keycode::AcForward => Keycode::AcForward,
            keyboard::Keycode::AcStop => Keycode::AcStop,
            keyboard::Keycode::AcRefresh => Keycode::AcRefresh,
            keyboard::Keycode::AcBookmarks => Keycode::AcBookmarks,
            keyboard::Keycode::SoftLeft => Keycode::SoftLeft,
            keyboard::Keycode::SoftRight => Keycode::SoftRight,
            keyboard::Keycode::Call => Keycode::Call,
            keyboard::Keycode::EndCall => Keycode::EndCall,
        }
    }
}